apiVersion: apps/v1
kind: Deployment
metadata:
  name: sender
  namespace: default
  labels:
    app: sender
  annotations:
    argocd-image-updater.argoproj.io/image-list: dotnetacrnick.azurecr.io/dotnet-sender
    argocd-image-updater.argoproj.io/dotnet-sender.update-strategy: latest
    argocd-image-updater.argoproj.io/dotnet-sender.pull-secret: pullsecret:argocd/acr-creds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sender
  template:
    metadata:
      labels:
        app: sender
    spec:
      containers:
        - name: sender
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
