apiVersion: v1
kind: Service
metadata:
  name: message-receiver-service
spec:
  type: NodePort
  selector:
    app: message-receiver
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30012

