apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-sender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-sender
  template:
    metadata:
      labels:
        app: message-sender
    spec:
      containers:
        - name: sender
          image: messagesender:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
